export const TICKET_LIST_REQUEST = "TICKET_LIST_REQUEST";
export const TICKET_LIST_FETCHING = "TICKET_LIST_FETCHING";
export const TICKET_LIST_SUCCESS = "TICKET_LIST_SUCCESS";
export const TICKET_LIST_FAILED = "TICKET_LIST_FAILED";

export const STATUS_LIST_REQUEST = "STATUS_LIST_REQUEST";
export const STATUS_LIST_FETCHING = "STATUS_LIST_FETCHING";
export const STATUS_LIST_SUCCESS = "STATUS_LIST_SUCCESS";
export const STATUS_LIST_FAILED = "STATUS_LIST_FAILED";

export const STATUS_BY_ID_LIST_REQUEST = "STATUS_BY_ID_LIST_REQUEST";
export const STATUS_BY_ID_LIST_FETCHING = "STATUS_BY_ID_LIST_FETCHING";
export const STATUS_BY_ID_LIST_FAILED = "STATUS_BY_ID_LIST_FAILED";
export const STATUS_BY_ID_LIST_SUCCESS = "STATUS_BY_ID_LIST_SUCCESS";

export const TICKET_CREATE_REQUEST = "TICKET_CREATE_REQUEST";
export const TICKET_CREATE_FETCHING = "TICKET_CREATE_FETCHING";
export const TICKET_CREATE_SUCCESS = "TICKET_CREATE_SUCCESS";
export const TICKET_CREATE_FAILED = "TICKET_CREATE_FAILED";

export const TICKET_EDIT_REQUEST = "TICKET_EDIT_REQUEST";
export const TICKET_EDIT_FETCHING = "TICKET_EDIT_FETCHING";
export const TICKET_EDIT_FAILED = "TICKET_EDIT_FAILED";
export const TICKET_EDIT_SUCCESS = "TICKET_EDIT_SUCCESS";

export const TICKET_DELETE_REQUEST = "TICKET_DELETE_REQUEST";
export const TICKET_DELETE_FETCHING = "TICKET_DELETE_FETCHING";
export const TICKET_DELETE_FAILED = "TICKET_DELETE_FAILED";
export const TICKET_DELETE_SUCCESS = "TICKET_DELETE_SUCCESS";
